services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: fastapi_db
      MYSQL_USER: fastapi_user
      MYSQL_PASSWORD: fastapi_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    environment:
      DATABASE_URL: mysql://fastapi_user:fastapi_password@db:3306/fastapi_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_PORT=3306

volumes:
  dbdata:
